[package]
name = "mdbook-blacksmith"
version = "0.1.0"
edition = "2018"
description = "A mdbook preprocessor for generating dynamic content for Rust Forge."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = { version = "0.3.1", features = ["search"] }
clap = "2.33.0"
reqwest = "0.9.20"
serde = { version = "1.0.99", features = ["derive"] }
regex = "1.2.1"
toml = "0.5.3"
serde_json = "1.0.40"
log = "0.4.8"
env_logger = "0.6.2"
