[book]
authors = ["The Rust Programming Language Team & Community"]
description = "Supplemental documentation for contributing to The Rust Programming Language"
language = "en"
src = "src"
title = "Rust Forge"

[preprocessor.blacksmith]
command = "./build.bash"

[output.html]
additional-js = ["js/moment.min.js", "js/index.js"]
no-section-label = true
git-repository-url = "https://github.com/rust-lang/rust-forge"
edit-url-template = "https://github.com/rust-lang/rust-forge/edit/master/{path}"
curly-quotes = true

[output.html.redirect]
"beta-backporting.html" = "/release/backporting.html"
"release/beta-backporting.html" = "/release/backporting.html"
"bibliography.html" = "https://rustc-dev-guide.rust-lang.org/appendix/bibliography.html"
"channel-layout.html" = "/infra/channel-layout.html"
"debugging.html" = "https://rustc-dev-guide.rust-lang.org/compiler-debugging.html"
"feature_guide.html" = "https://rustc-dev-guide.rust-lang.org/implementing_new_features.html"
"fott.html" = "/archive/fott.html"
"infrastructure.html" = "/infra/service-infrastructure.html"
"other-installation-methods.html" = "/infra/other-installation-methods.html"
"platform-support.html" = "https://doc.rust-lang.org/nightly/rustc/platform-support.html"
"release/platform-support.html" = "https://doc.rust-lang.org/nightly/rustc/platform-support.html"
"profile-queries.html" = "/compiler/profile-queries.html"
"release-notes.html" = "/release/release-notes.html"
"releases.html" = "/archive/release-history.html"
"rfc-merge-procedure.html" = "/lang/rfc-merge-procedure.html"
"rustc-bug-fix-procedure.html" = "/compiler/bug-fix-procedure.html"
"rustc-diagnostic-code.html" = "/compiler/diagnostic-codes.html"
"rustc-team-maintenance.html" = "/infra/team-maintenance.html"
"stabilization-guide.html" = "https://rustc-dev-guide.rust-lang.org/stabilization_guide.html"
"state-of-rust.html" = "https://github.com/rust-lang/rust/projects/8"
"test-suite.html" = "https://rustc-dev-guide.rust-lang.org/tests/intro.html"
"toolstate.html" = "/infra/toolstate.html"
"triage-procedure.html" = "/release/triage-procedure.html"
"x-py.html" = "https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html"
"compiler/bug-fix-procedure.html" = "https://rustc-dev-guide.rust-lang.org/bug-fix-procedure.html"
"compiler/diagnostic-codes.html" = "https://rustc-dev-guide.rust-lang.org/diagnostics/diagnostic-codes.html"
"compiler/mcp.html" = "https://rustc-dev-guide.rust-lang.org/compiler/proposals-and-stabilization.html"
"compiler/new_option.html" = "https://rustc-dev-guide.rust-lang.org/compiler/proposals-and-stabilization.html"
"compiler/prioritization/priority-levels.html" = "https://rustc-dev-guide.rust-lang.org/compiler/prioritization.html"
"compiler/prioritization/procedure.html" = "https://rustc-dev-guide.rust-lang.org/compiler/prioritization.html"
"compiler/profile-queries.html" = "https://rustc-dev-guide.rust-lang.org/queries/profiling.html"
"compiler/steering-meeting.html" = "https://rustc-dev-guide.rust-lang.org/compiler/meetings.html"
"compiler/steering-meeting/how-to-run-design.html" = "https://rustc-dev-guide.rust-lang.org/compiler/meetings.html"
"compiler/steering-meeting/how-to-run-planning.html" = "https://rustc-dev-guide.rust-lang.org/compiler/meetings.html"
"compiler/steering-meeting/submit.html" = "https://rustc-dev-guide.rust-lang.org/compiler/meetings.html"
"compiler/triage-meeting.html" = "https://rustc-dev-guide.rust-lang.org/compiler/meetings.html"
"chat/index.html" = "/platforms/index.html"
"chat/discord.html" = "/platforms/discord.html"
"github.html" = "/platforms/github.html"
"chat/email.html" = "/platforms/email.html"
"chat/zulip/index.html" = "/platforms/zulip/index.html"
"chat/zulip.html" = "/platforms/zulip.html"
"platforms/zulip/triagebot.html" = "/triagebot/index.html"
"core/blogs.html" = "/platforms/blogs.html"
"core/index.html" = "/governance/council.html"
